/* 
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cli
 */
public class Poker extends javax.swing.JFrame {

    /**
     * Creates new form Poker
     */
    int diceThrows;
    int playNr;
        
    public Poker() {
        initComponents();
        initDie();
        initPlayer();
        this.pack();
    }
    
    public void initDie(){
        dice = new Dice[5];
        for (int i = 0; i<5; i++){
            dice[i] = new Dice();
            jPanel1.add(dice[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(40*i, 50, 35, 35));
            dice[i].addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Dice d =(Dice)evt.getSource();
                }
            });
        }
        diceThrows=3;
    }
    
    public void initPlayer(){
        
        player = new Player[2];
        for (int i = 0; i<2; i++){
            player[i] = new Player();
            getContentPane().add(player[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(20+i*400, 50, 150, 600));
        }
        
        player[0].addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
               if(!player[0].isEnabled()) {
                   playNr=1;
                   //nextMove();
               }                
            }
        });
        
        player[1].addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
               if(!player[1].isEnabled()) {
                   playNr=0;
                   //nextMove();
               }                
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 220, 194));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(diceThrows==3){
           player[playNr].setVisible(true);
           player[1-playNr].setVisible(false);
           for(int i=0;i<dice.length;i++){
             dice[i].setSelected(false);  
             dice[i].setEnabled(true);
           }
        }
        int[] points=new int[5];
        for(int i=0;i<dice.length;i++){
            if(!dice[i].isSelected()){
                dice[i].throwDice();
            }
            points[i]=dice[i].getN();
        }
        player[playNr].setPoints(new Combinations(points).getPoints());
        diceThrows--;
        if(diceThrows==0){
            jButton1.setEnabled(false);
            diceThrows=3;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poker().setVisible(true);
            }
        });
    }

    
    
    private Dice[] dice;
    private Player[] player;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
